### ISSUE TITLE
Get the command output

### ISSUE THREAD

**Issue by arnaudluti** [1lann/log4shelldetect#5]
Hi @1lann and thanks for the work,
I already used your tool to scan individually some of our servers.

I wanted to scan the whole infrastructure by executing the tool with jobs on more computers, remotely.
To get the vulnerable binaries/detections & grep the output, i need to save the output of your tool in a file.

I tried everything with DOS & PowerShell without success : Out-File, RedirectStandardOutput, *>, PS Transcript... Every file i try to write keeps empty.

How can i get the output of your tool in a file ?
Thanks in advance

*Edit* : it seems to work with -mode report, not with -mode list

**Comment by 1lann** [comment]
`-mode list` will only output vulnerable files. Non-vulnerable files are not reported. Do you have any vulnerable files on the systems you're scanning?

**Comment by arnaudluti** [comment]
oh, ok. Even if the errors (access denied...) are logged in stdout, only lines that contains the detections are written in the out-file. So it's perfect... i stopped to the fact i couldn't see what i see in stdout in my out file...

**Comment by 1lann** [comment]
Haha yeah that's intentional, I designed it for easy automation in mind. I/O warnings are written to stderr so they can be suppressed and don't appear in pipe outputs by default. `-mode list` is clean and will _only_ ever output vulnerable file paths to stdout. You can also check the exit status code to determine if there were any hits.
